### ISSUE TITLE
What is the version of python3? My version is Python 3.6.12. An error is reported

### ISSUE THREAD

**Issue by happylife-666** [eniac/tpprof#1]

**Comment by NofelYaseen** [comment]
For python specific issues, please refer to [https://stackoverflow.com](https://stackoverflow.com).

In this case, you could try:
```
pip3 install --upgrade setuptools
```

It's taken from:  [https://stackoverflow.com/questions/47955397/pip3-error-namespacepath-object-has-no-attribute-sort](https://stackoverflow.com/questions/47955397/pip3-error-namespacepath-object-has-no-attribute-sort)

**Comment by happylife-666** [comment]
It's working. Thanks
