### ISSUE TITLE
About traffic pattern scoring

### ISSUE THREAD

**Issue by happylife-666** [eniac/tpprof#2]
Hello, Profession. You mentioned that  traffic Pattern Scoring was implemented in C++ using hyperscan. Is this source code open source? I have encountered some problems. Can I have a copy of the source code?  thank you very much.

**Comment by NofelYaseen** [comment]
I have added the scoring program in `snapGrep` folder with 2 examples. 
I'll add the readme file with installation instructions soon.

**Comment by NofelYaseen** [comment]
Readme file added in ```snapGrep``` folder for clarity
